vim.lsp.enable "dartls"
-- vim.lsp.enable "autotools_ls" -- Disable because of suggested memory leak
vim.lsp.enable "html"
vim.lsp.enable "cssls"
vim.lsp.enable "ts_ls"
vim.lsp.enable "emmet_language_server"
vim.lsp.enable "clangd"
vim.lsp.enable "texlab"
vim.lsp.enable "eslint"
vim.lsp.enable "marksman"
vim.lsp.enable "tailwindcss"
vim.lsp.enable "pyright"
vim.lsp.enable "ruff"
vim.lsp.enable "prismals"
vim.lsp.enable "sqlls"
vim.lsp.enable "terraformls"
vim.lsp.enable "gleam"
vim.lsp.enable "lua_ls"
vim.lsp.enable "gopls"
-- vim.lsp.enable "rust_analyzer"
vim.lsp.enable "rust-analyzer"
vim.lsp.enable "tinymist"
vim.lsp.enable "jsonls"
vim.lsp.enable "yamlls"
