return {
	-- "benlubas/molten-nvim",
	-- -- ft = {"python", "ipynb"},
	-- -- event = "VeryLazy",
	-- -- lazy = false,
	-- enable = false,
	-- -- ft = { "quarto", "markdown", "python" },
	-- ft = { "markdown", "ipynb" },
	-- version = "^1.0.0",
	-- build = ":UpdateRemotePlugins",
	-- dependencies = {
	-- 	{
	-- 		"willothy/wezterm.nvim",
	-- 		config = true,
	-- 	},
	-- 	{
	-- 		"quarto-dev/quarto-nvim",
	-- 		dependencies = {
	-- 			"jmbuhr/otter.nvim",
	-- 			"nvim-treesitter/nvim-treesitter",
	-- 		},
	-- 		opts = {
	-- 			codeRunner = {
	-- 				default_method = "molten",
	-- 			},
	-- 		},
	-- 	},
	-- 	{
	-- 		"GCBallesteros/jupytext.nvim",
	-- 		opts = {
	-- 			style = "markdown",
	-- 			output_extension = "md",
	-- 			force_ft = "markdown",
	-- 		},
	-- 		-- lazy = false,
	-- 	},
	-- },
	-- init = function()
	-- 	-- I find auto open annoying, keep in mind setting this option will require setting
	-- 	-- a keybind for `:noautocmd MoltenEnterOutput` to open the output again
	-- 	vim.g.molten_auto_open_output = true
	--
	-- 	-- this guide will be using image.nvim
	-- 	-- Don't forget to setup and install the plugin if you want to view image outputs
	-- 	vim.g.molten_image_provider = "wezterm"
	--
	-- 	-- optional, I like wrapping. works for virt text and the output window
	-- 	vim.g.molten_wrap_output = true
	--
	-- 	-- Output as virtual text. Allows outputs to always be shown, works with images, but can
	-- 	-- be buggy with longer images
	-- 	vim.g.molten_virt_text_output = true
	--
	-- 	-- this will make it so the output shows up below the \`\`\` cell delimiter
	-- 	vim.g.molten_virt_lines_off_by_1 = true
	-- end,
	-- config = function()
	-- 	local runner = require("quarto.runner")
	-- 	vim.keymap.set("n", "<localleader>rc", runner.run_cell, { desc = "run cell", silent = true })
	-- 	vim.keymap.set("n", "<localleader>ra", runner.run_above, { desc = "run cell and above", silent = true })
	-- 	vim.keymap.set("n", "<localleader>rA", runner.run_all, { desc = "run all cells", silent = true })
	-- 	vim.keymap.set("n", "<localleader>rl", runner.run_line, { desc = "run line", silent = true })
	-- 	vim.keymap.set("v", "<localleader>r", runner.run_range, { desc = "run visual range", silent = true })
	-- 	vim.keymap.set("n", "<localleader>RA", function()
	-- 		runner.run_all(true)
	-- 	end, { desc = "run all cells of all languages", silent = true })
	--
	-- 	require("quarto").activate()
	--
	-- 	-- local imb = function(e) -- init molten buffer
	-- 	-- 	vim.schedule(function()
	-- 	-- 		local kernels = vim.fn.MoltenAvailableKernels()
	-- 	-- 		local try_kernel_name = function()
	-- 	-- 			local metadata = vim.json.decode(io.open(e.file, "r"):read("a"))["metadata"]
	-- 	-- 			return metadata.kernelspec.name
	-- 	-- 		end
	-- 	-- 		local ok, kernel_name = pcall(try_kernel_name)
	-- 	-- 		if not ok or not vim.tbl_contains(kernels, kernel_name) then
	-- 	-- 			kernel_name = nil
	-- 	-- 			local venv = os.getenv("VIRTUAL_ENV") or os.getenv("CONDA_PREFIX")
	-- 	-- 			if venv ~= nil then
	-- 	-- 				kernel_name = string.match(venv, "/.+/(.+)")
	-- 	-- 			end
	-- 	-- 		end
	-- 	-- 		if kernel_name ~= nil and vim.tbl_contains(kernels, kernel_name) then
	-- 	-- 			vim.cmd(("MoltenInit %s"):format(kernel_name))
	-- 	-- 		end
	-- 	-- 		vim.cmd("MoltenImportOutput")
	-- 	-- 	end)
	-- 	-- end
	-- 	--
	-- 	-- -- automatically import output chunks from a jupyter notebook
	-- 	-- vim.api.nvim_create_autocmd("BufAdd", {
	-- 	-- 	pattern = { "*.ipynb" },
	-- 	-- 	callback = imb,
	-- 	-- })
	-- 	--
	-- 	-- -- we have to do this as well so that we catch files opened like nvim ./hi.ipynb
	-- 	-- vim.api.nvim_create_autocmd("BufEnter", {
	-- 	-- 	pattern = { "*.ipynb" },
	-- 	-- 	callback = function(e)
	-- 	-- 		if vim.api.nvim_get_vvar("vim_did_enter") ~= 1 then
	-- 	-- 			imb(e)
	-- 	-- 		end
	-- 	-- 	end,
	-- 	-- })
	-- end,
	-- keys = {
	-- 	{ "<leader>mma", "<cmd>MoltenEvaluateOperator<cr>", desc = "molten evaluate operator" },
	-- 	{ "<leader>mmo", "<cmd>noautocmd MoltenEnterOutput<cr>", desc = "open output window" },
	-- },
}
